#!/bin/bash
#install-packages curl wget linux-libc-dev git gcc libc6-dev bridge-utils haproxy ntp ntpdate

SVC_ROOT=/opt/bin

MCP_REGISTRY_URI="mcp-ci.ng.mirantis.net:5002"
MCP_IMAGE_NAME="hyperkube-amd64"
MCP_IMAGE_TAG="v1.4.0-alpha.2-1582-ge32e1b_51"
ETCD_LATEST_VERSION="v3.0.4"
FLANNEL_LATEST_VERSION="v0.5.5"

ETCD_LATEST_URL="https://github.com/coreos/etcd/releases/download/${ETCD_LATEST_VERSION}/etcd-${ETCD_LATEST_VERSION}-linux-amd64.tar.gz"
FLANNEL_LATEST_URL="https://github.com/coreos/flannel/archive/${FLANNEL_LATEST_VERSION}.tar.gz"

mkdir -p ${SVC_ROOT}
pushd ${SVC_ROOT}

# Install latest etcd
wget -O ${SVC_ROOT}/etcd-latest.tar.gz $ETCD_LATEST_URL
tar xzvf ${SVC_ROOT}/etcd-latest.tar.gz
rm -f ${SVC_ROOT}/etcd-latest.tar.gz
mv ${SVC_ROOT}/etcd-${ETCD_LATEST_VERSION}-linux-amd64/etcd ${SVC_ROOT}/
mv ${SVC_ROOT}/etcd-${ETCD_LATEST_VERSION}-linux-amd64/etcdctl ${SVC_ROOT}/
rm -rf ${SVC_ROOT}/etcd-${ETCD_LATEST_VERSION}-linux-amd64

# Install latest kubernetes and calico from MCP image. MCP registry should be available
service docker start 

docker pull ${MCP_REGISTRY_URI}/${MCP_IMAGE_NAME}:${MCP_IMAGE_TAG}
CONTAINER_ID=`docker ps --no-trunc -q`
docker cp ${CONTAINER_ID}:/hyperkube ${SVC_ROOT}
docker cp ${CONTAINER_ID}:/make-ca-cert.sh /
docker cp ${CONTAINER_ID}:/setup-files.sh /
docker cp ${CONTAINER_ID}:/etc/kubernetes ${SVC_ROOT}
CERTS=`./setup-files.sh 127.0.0.1`
docker rmi -f ${MCP_REGISTRY_URI}/${MCP_IMAGE_NAME}:${MCP_IMAGE_TAG}
rm /make-ca-cert.sh /setup-files.sh

docker cp ${CONTAINER_ID}:/opt/cni ${SVC_ROOT}

# Install calico
#TBD

# Install Go
wget -O go.tar.gz https://storage.googleapis.com/golang/go1.6.2.linux-amd64.tar.gz
tar xzvf go.tar.gz
mv ${SVC_ROOT}/go /usr/local/go
export PATH=$PATH:/usr/local/go/bin

# Build flannel
wget -O ${SVC_ROOT}/flannel-latest.tar.gz $FLANNEL_LATEST_URL
tar xzvf ${SVC_ROOT}/flannel-latest.tar.gz
rm -f ${SVC_ROOT}/flannel-latest.tar.gz
mv ${SVC_ROOT}/flannel-* ${SVC_ROOT}/flannel
pushd ${SVC_ROOT}/flannel
${SVC_ROOT}/flannel/build
popd
cp ${SVC_ROOT}/flannel/bin/flanneld ${SVC_ROOT}/flanneld
rm -rf ${SVC_ROOT}/flannel

# Update system PATH
sed -i 's/PATH="/PATH="\/opt\/bin:\/opt\/go\/bin:/g' /etc/environment
wget -O confd https://github.com/kelseyhightower/confd/releases/download/v0.7.1/confd-0.7.1-linux-amd64
mv confd /usr/local/bin/confd
chmod +x /usr/local/bin/confd
mkdir -p /etc/confd/{conf.d,templates}

popd

if [[ $(lsb_release -c -s) == 'jessie' ]]; then
 #Enable cgroup memory if Debian 8 is used. Required by k8s since 1.2
 echo 'GRUB_CMDLINE_LINUX="cgroup_enable=memory swapaccount=1"' >> /etc/default/grub

 #Do not start haproxy on vm boot
 systemctl disable haproxy
fi
