#!/bin/bash

set -eu

install-packages curl
curl -sSL https://get.docker.com/ | sh

echo 'DOCKER_OPTS="--bip=172.31.0.1/16 --fixed-cidr=172.31.0.0/16 --mtu=1450"' >> /etc/default/docker
if [[ $(lsb_release -c -s) == 'jessie' ]]; then
 # On debian docker ignores /etc/default/docker file
 # Modifying docker.service to add reference to config file
 sed -i '/Type=notify/a EnvironmentFile=-/etc/default/docker' /lib/systemd/system/docker.service
 sed -i 's/fd:\/\//fd:\/\/ $DOCKER_OPTS/g' /lib/systemd/system/docker.service
fi
